# Generated by Django 5.1.7 on 2025-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('luxury', 'Люкс'), ('electric', 'Электро')], default='standard', max_length=20),
        ),
    ]
