# Generated by Django 5.1.7 on 2025-04-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_vin_number_alter_car_price_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vin_number',
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
