# Generated by Django 5.2 on 2025-04-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reviews_avg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='car',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
